language: python
python:
- '3.6'
cache: pip
install:
- pip install -r requirements.txt
script:
- python tests.py
env:
  global:
  - secure: wi6rgA4PKqiNs6xCSLOJr97ZzaYgvQ4SkVCEQJGyRJRk7sVtTIBHJ/M7G833bskCTG5X/1nsKy6MeOS1RzKZJJTHLczucCmPMZr84prS7+dCz/SVc/dliSrtajx7pOLcgBUPj/CmYncbWyaAKDqhgy9dxoWPzNu2aQZLbAd+VSUW0g6KouJlT4paF/8+I4pqEBPRlW3lV8P8np/DtUbJdmIwtpJ/khHQCDRYhyedPSsDEIpC+GRgMDcHiqOS0Bx6nSRmLlVWA+foVqqgLOy5jXdtBjXYxIEmGPgzJI5EqLRUMnDePG7Iq5v7NR4mVbQ6So4VtUPfLW220yCzuDc+uVN9WpYdeOPVFoYsQ0SZkr215frUWtBmEVmfG4X6Id0hxfvEm8JFCEElDgi5cq/eAECQN70UhFp1XJkRJRaaAxIdn8t3t4aa0ZQlrVhDQu+9ygc1wm8fN++Zb6y3SiPiczW8vBUKGIhu97ksl/XdblJSP8a8V+4Lkl5kRa0GdKRyV6Z6E2ypbX+KKWWDktsXiB/rQG7ePmWPDb65fOSUv5tmY+q/IFCq+TAUxUDUMLyZX4K1hTSyLi3nszYJMH/hFoaqIEo4HTfr4XPHYvAl3pETLQzu7Px7JGg/jQX/gq8Lfl+CZFbjfnlV5cgAKzsTaBuNetTWbjnskxGvUtqdS18=
  - secure: xByAECU18rPMXpdw+Q990fzBLtTYTwQFmaeGH/neefMZowbO6D4z34Lm7uOgykMypw7Ar5NZIDCVWStbv0H20nkgYOzM8FgPDF9aYSr33s7CJb5dMm8KeL0JtpB2TuKW+L7D/YxeMRtfAjlTqFwVCboocsKqC8tKQvHkjOPGgukSFPtFnD/BgRImh1meRAPbxj/ZD58mOS14yPho/u07cNzYIoy+7zubvPDTg4YbQJ1A9LIHKxm7HEaE1ZQ1PcEoGg1vImAIklSr2XOTIhs16djs0w7AnLQ94PBCbVJJGaeLwrlUF64mxP8Jkq47rR82QuKlaTBtDR/14goSnpyJmkt/Fp7J3JV6RV4/PyksQBpnic0EdPt2q7bsBywnuc/RUt9GbXbG2NFGT7m7pz4nPRSzueAXOAZ/4WWcGimCf7jXD+/qvbZ1YhQ4wJ62FsO72ndmKQ3ZWYdGR2Ei0FotsyVPeOtCyjW9I82HQ9n5BMsp2y6FT0fD5FA4KBFq1Lzf5q+wz5wLcLRVV3CG36/oSFachs2C34TpEmki0oQLKFjg8ZaENXaUBWFvO65K25UQazgmielzZlCa6blVH6xvZ5YHi/ZNv/MVtQ/J5E80NN1WDApC7dpqOriaTsB4QJ+Ec729MB00JyHS0mdZC55k/JNTOWq5JHN4P7ukPnunrN0=
